In [6]:
# Import Libraries
import pandas as pd

# Read in the data
sleep_df = pd.read_csv('data//sleep_health_data.csv')

# View the data
sleep_df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [15]:
# Find the occupation with the lowest sleep average
sleep_occupation = sleep_df.groupby('Occupation')['Sleep Duration'].mean()

# Sort the occupations by the mean sleep duration
lowest_sleep_occ = mean_sleep_duration.sort_values().index[0]

In [16]:
# Which occupation had the lowest quality of sleep? Did this align with lowest sleep?
sleep_quality = sleep_df.groupby('Occupation')['Quality of Sleep'].mean()

# Get the occupation with the lowest quality of sleep
lowest_sleep_quality_occ = sleep_quality.sort_values().index[0]

In [29]:
# Compare the occupation with the least sleep to occupation with the lowest sleep quality
if lowest_sleep_occ == lowest_sleep_quality_occ:
    same_occ = True
else:
    same_occ = False
print(same_occ)

# View the occupation
print("The lowest sleep duration is:", lowest_sleep_occ)
print("The lowest sleep quality is:", lowest_sleep_quality_occ)

True
The lowest sleep duration is: Sales Representative
The lowest sleep quality is: Sales Representative

In [30]:
# How does BMI affect sleep
# Filter the data by Normal, Overweight, and Obese
normal = sleep_df[(sleep_df['BMI Category'] == 'Normal') & (sleep_df['Sleep Disorder'] == 'Insomnia')]
normal_2 = sleep_df[(sleep_df['BMI Category'] == 'Normal Weight') & (sleep_df['Sleep Disorder'] == 'Insomnia')]

# Get a total for normal
total_normal = len(sleep_df[sleep_df['BMI Category'] == 'Normal'])
# Calculate normal insomnia ratio
normal_insomnia_ratio = round(len(normal) / total_normal, 2)

# Overweight
overweight = sleep_df[(sleep_df["BMI Category"] == "Overweight") &   
                      (sleep_df["Sleep Disorder"] == "Insomnia")]  
# Total overweight rows
total_overweight = len(sleep_df[sleep_df["BMI Category"] == "Overweight"])  
# Calculate overweight insomnia ratio 
overweight_insomnia_ratio = round(len(overweight) / total_overweight, 2)


# Obese
# Filter the full dataframe to only rows where BMI Category is Obese and Sleep Disorder is Insomnia.
obese = sleep_df[(sleep_df["BMI Category"] == "Obese") &  
                  (sleep_df["Sleep Disorder"] == "Insomnia")]
# Total obese rows          
total_obese = len(sleep_df[sleep_df["BMI Category"] == "Obese"])  
# Calculate obese insomnia ratio
obese_insomnia_ratio = round(len(obese) / total_obese, 2)

In [31]:
# Create a dictionary to store the BMI ratios
bmi_insomnia_ratios = {
    "Normal": normal_insomnia_ratio,
    "Overweight": overweight_insomnia_ratio,
    "Obese": obese_insomnia_ratio
}

print(bmi_insomnia_ratios)

{'Normal': 0.04, 'Overweight': 0.43, 'Obese': 0.4}